name: Build Custom RustDesk APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
        channel: 'stable'
    
    - name: Clone RustDesk
      run: |
        git clone https://github.com/rustdesk/rustdesk.git
        cd rustdesk/flutter
    
    - name: Setup configuration
      run: |
        mkdir -p rustdesk/flutter/android/app/src/main/assets
        cp rustdesk_config.toml rustdesk/flutter/android/app/src/main/assets/rustdesk.toml
    
    - name: Modify app identity
      run: |
        cd rustdesk/flutter
        sed -i 's/applicationId "com.carriez.flutter_hbb"/applicationId "com.custom.rustdesk"/' android/app/build.gradle
        sed -i 's/android:label="RustDesk"/android:label="CustomRustDesk"/' android/app/src/main/AndroidManifest.xml
    
    - name: Build APK
      run: |
        cd rustdesk/flutter
        flutter pub get
        flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: CustomRustDesk-APK
        path: rustdesk/flutter/build/app/outputs/flutter-apk/app-release.apk
